version: '3.1'
services:
  app:
    container_name: app
    image: fav-things-service.jar
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5